# Generated by Django 5.0 on 2023-12-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarefa', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
